# Generated by Django 6.0.6 on 2026-06-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategoriya', models.CharField(choices=[('oziq-ovqat', 'Oziq-ovqat'), ('kiyim', 'Kiyim'), ('texnika', 'Texnika')], max_length=50)),
                ('soni', models.PositiveIntegerField()),
                ('faol', models.BooleanField(default=True)),
                ('tavsif', models.TextField(blank=True)),
                ('qoshilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
    ]
