# Generated by Django 6.0.6 on 2026-06-04 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_group_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=120)),
                ('tugilgan_yili', models.IntegerField()),
                ('davlat', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='group',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('til', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('en', 'Ingliz')], default='uz', max_length=2)),
                ('nashr_yili', models.IntegerField()),
                ('narx', models.DecimalField(decimal_places=2, max_digits=9)),
                ('mavjud', models.BooleanField(default=True)),
                ('qoshilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('janrlar', models.ManyToManyField(to='main.janr')),
                ('muallif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.muallif')),
            ],
        ),
        migrations.CreateModel(
            name='KitobNusxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventar_raqami', models.CharField(max_length=50)),
                ('holati', models.CharField(choices=[('javonda', 'Javonda'), ('berilgan', 'Berilgan'), ('yoqolgan', "Yo'qolgan")], default='javonda', max_length=20)),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kitob')),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
