# Generated by Django 6.0.6 on 2026-06-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_maqola_delete_mahsulot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('guruh', models.CharField(max_length=50)),
                ('yosh', models.PositiveIntegerField()),
                ('faol', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Maqola',
        ),
    ]
