# Generated by Django 6.0.6 on 2026-06-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_janr_muallif_remove_room_branch_remove_group_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='janr',
            options={'verbose_name': 'Janr', 'verbose_name_plural': 'Janrlar'},
        ),
        migrations.AlterModelOptions(
            name='kitob',
            options={'verbose_name': 'Kitob', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='kitobnusxa',
            options={'verbose_name': 'Kitob Nusxasi', 'verbose_name_plural': 'Kitob Nusxalari'},
        ),
        migrations.AlterModelOptions(
            name='muallif',
            options={'verbose_name': 'Muallif', 'verbose_name_plural': 'Mualliflar'},
        ),
    ]
