# Generated by Django 6.0.6 on 2026-06-04 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_janr_options_alter_kitob_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='janr',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kitob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kitobnusxa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='muallif',
            options={},
        ),
        migrations.AlterField(
            model_name='janr',
            name='nomi',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='kitobnusxa',
            name='holati',
            field=models.CharField(choices=[('javonda', 'Javonda'), ('berilgan', 'Berilgan'), ('yoʻqolgan', 'Yoʻqolgan')], default='javonda', max_length=15),
        ),
        migrations.CreateModel(
            name='Ijara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oluvchi', models.CharField(max_length=120)),
                ('olingan_sana', models.DateField()),
                ('qaytarilgan', models.BooleanField(default=False)),
                ('nusxa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kitobnusxa')),
            ],
        ),
    ]
