# Generated by Django 5.2.14 on 2026-06-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_janr_options_alter_kitob_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KursAriza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toliq_ism', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('yosh', models.PositiveIntegerField()),
                ('yonalish', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('dizayn', 'Dizayn')], max_length=20)),
                ('tajriba_bor', models.BooleanField(default=False)),
                ('qoshimcha', models.TextField(blank=True)),
                ('yuborilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='kitob',
            name='janrlar',
        ),
        migrations.RemoveField(
            model_name='kitob',
            name='muallif',
        ),
        migrations.RemoveField(
            model_name='kitobnusxa',
            name='kitob',
        ),
        migrations.DeleteModel(
            name='Ijara',
        ),
        migrations.DeleteModel(
            name='Janr',
        ),
        migrations.DeleteModel(
            name='Muallif',
        ),
        migrations.DeleteModel(
            name='Kitob',
        ),
        migrations.DeleteModel(
            name='KitobNusxa',
        ),
    ]
